	<form:option value="" label="--- Select Country ---" />
    <form:option value="Argentina">Argentina</form:option>
    <form:option value="Australia">Australia</form:option>
    <form:option value="Austria">Austria</form:option>
    <form:option value="Bahrain">Bahrain</form:option>
    <form:option value="Bangladesh">Bangladesh</form:option>
    <form:option value="Belgium">Belgium</form:option>
    <form:option value="Brazil">Brazil</form:option>
    <form:option value="Bulgaria">Bulgaria</form:option>
    <form:option value="Canada">Canada</form:option>
    <form:option value="China">China</form:option>
    <form:option value="Colombia">Colombia</form:option>
    <form:option value="Denmark">Denmark</form:option>
    <form:option value="Egypt">Egypt</form:option>
    <form:option value="Finland">Finland</form:option>
    <form:option value="France">France</form:option>
    <form:option value="Georgia">Georgia</form:option>
    <form:option value="Germany">Germany</form:option>
    <form:option value="Greece">Greece</form:option>
    <form:option value="Hong Kong">Hong Kong</form:option>
    <form:option value="Hungary">Hungary</form:option>
    <form:option value="Iceland">Iceland</form:option>
    <form:option value="India">India</form:option>
    <form:option value="Indonesia">Indonesia</form:option>
    <form:option value="Iran">Iran (Islamic Republic of)</form:option>
    <form:option value="Iraq">Iraq</form:option>
    <form:option value="Ireland">Ireland</form:option>
    <form:option value="Israel">Israel</form:option>
    <form:option value="Italy">Italy</form:option>
    <form:option value="Japan">Japan</form:option>
    <form:option value="Jordan">Jordan</form:option>
    <form:option value="Democratic People's Republic of Korea">Korea, Democratic People's Republic of</form:option>
    <form:option value="Korea">Korea, Republic of</form:option>
    <form:option value="Kuwait">Kuwait</form:option>
    <form:option value="Luxembourg">Luxembourg</form:option>
    <form:option value="Macau">Macau</form:option>
    <form:option value="Malaysia">Malaysia</form:option>
    <form:option value="Maldives">Maldives</form:option>
    <form:option value="Mauritius">Mauritius</form:option>
    <form:option value="Mexico">Mexico</form:option>
    <form:option value="Monaco">Monaco</form:option>
    <form:option value="Myanmar">Myanmar</form:option>
    <form:option value="Nepal">Nepal</form:option>
    <form:option value="Netherlands">Netherlands</form:option>
    <form:option value="New Zealand">New Zealand</form:option>
    <form:option value="Norway">Norway</form:option>
    <form:option value="Oman">Oman</form:option>
    <form:option value="Pakistan">Pakistan</form:option>
    <form:option value="Paraguay">Paraguay</form:option>
    <form:option value="Philippines">Philippines</form:option>
    <form:option value="Poland">Poland</form:option>
    <form:option value="Portugal">Portugal</form:option>
    <form:option value="Qatar">Qatar</form:option>
    <form:option value="Romania">Romania</form:option>
    <form:option value="Russia">Russian Federation</form:option>
    <form:option value="Saudi Arabia">Saudi Arabia</form:option>
    <form:option value="Seychelles">Seychelles</form:option>
    <form:option value="Singapore">Singapore</form:option>
    <form:option value="South Africa">South Africa</form:option>
    <form:option value="Spain">Spain</form:option>
    <form:option value="SriLanka">Sri Lanka</form:option>
    <form:option value="Sweden">Sweden</form:option>
    <form:option value="Switzerland">Switzerland</form:option>
    <form:option value="Syria">Syrian Arab Republic</form:option>
    <form:option value="Taiwan">Taiwan, Province of China</form:option>
    <form:option value="Thailand">Thailand</form:option>
    <form:option value="Ukraine">Ukraine</form:option>
    <form:option value="United Arab Emirates">United Arab Emirates</form:option>
    <form:option value="United Kingdom">United Kingdom</form:option>
    <form:option value="United States">United States</form:option>
    <form:option value="United States Minor Outlying Islands">United States Minor Outlying Islands</form:option>
    <form:option value="Uruguay">Uruguay</form:option>
    <form:option value="Venezuela">Venezuela</form:option>
    <form:option value="Yugoslavia">Yugoslavia</form:option>
    <form:option value="Zambia">Zambia</form:option>
    <form:option value="Zimbabwe">Zimbabwe</form:option>
